name: Generate Release Documentation

on: [ workflow_dispatch, repository_dispatch ]

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Command Handler
        uses: actions/checkout@v2
        with:
          repository: Advanced-Command-Handler/Advanced-Command-Handler
          path: 'source'
      - run: |
          git fetch --tags
          latesttag=$(git describe --tags)
          echo checking out ${latesttag}
          git checkout ${latesttag}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm i

      - name: Install source Dependencies
        run: |
          cd source
          npm i

      - name: Format & Lint
        run: |
          cd source
          npm run prettier
          npm run lint

      - name: Generate Documentation
        run: npm run generateRelease

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add docs-release -f
          git commit -m "docs: Generate documentation."
          git push origin master
