name: Generate Release Documentation

on: [ workflow_dispatch, repository_dispatch ]

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest release with tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/Advanced-Command-Handler/Advanced-Command-Handler/releases/latest | jq '.tag_name' | sed 's/\"//g')"

      - name: Confirm release tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}

      - name: Download Project in latest tag
        uses: actions/checkout@v2
        with:
          repository: Advanced-Command-Handler/Advanced-Command-Handler
          path: 'source'
          ref: ${{ steps.latestrelease.outputs.releasetag }}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm i

      - name: Install source Dependencies
        run: |
          cd source
          npm i

      - name: Format & Lint
        run: |
          cd source
          npm run prettier
          npm run lint

      - name: Generate Documentation
        run: npm run generateRelease

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add docs-release -f
          git commit -m "docs: Generate documentation."
          git push origin master
